### ISSUE TITLE
Troubles auto-loading

### ISSUE THREAD

**Issue by freetonik** [balddotcat/ox-slimhtml#3]
I'm not sure if this is a problem with my config. Can you provide an example of loading ox-slimhtml into your Emacs?

For some reason, if `(load ox-slimhtml)` is a part of my config, it does not load the package properly. If I go and run this command manually, it works.

**Comment by balddotcat** [comment]
I think you're looking for `(require 'ox-slimhtml)`; the first argument to `load` is a path, as a string - in the above, does the variable `ox-slimhtml` refer to the path of the file itself?

The `require` statement should be preceded with call to `(and (require 'package) (package-initialize))` in your init file, or otherwise - this sets up the `package` environment. 

When installing with `M-x package-install`, Emacs usually takes care of updating `custom.el` for you, and updates `load-path` - which, if you're still having problems, is what I would check next.

Personally, I use `M-x load-library` to load a packages into the current environment, as required.

**Comment by freetonik** [comment]
Yeah, sorry, that was just a typo. I meant`(require 'ox-slimhtml)`.

If I install the package manually and add `(require 'ox-slimhtml)` to my init-file (all the way after all other packages are installed and after `(package-initialize)`), it doesn't load on startup. If I then go and execute `(load 'ox-slimhtml)` manually, it works.

If I use `use-package` like so

```
(use-package ox-slimhtml
  :ensure t)
```

then it works in the session right after the installation, but doesn't load on startup either. 

I wonder if this is something to do with [my config](https://github.com/freetonik/emacs-dotfiles), but other packages load and work as expected...

**Comment by freetonik** [comment]
I should clarify: by "doesn't load" I mean the backend is not loaded (?) If I try `(org-export-to-buffer 'slimhtml "*slimhtml*")`, I get the error:

```
Unknown "nil" back-end: Aborting export
```

So, `'slimhtml` is not defined, and if I do this:

```
(org-export-define-derived-backend 'custom-html-exporter
        'slimhtml                             ;; org's default exporter is 'html
      :translate-alist
      '((bold . ox-slimhtml-bold)             ;; technically, this is already set
        (special-block . org-html-special-block)))
```

I get this:

```
Debugger entered--Lisp error: (error "Cannot use unknown \"slimhtml\" back-end as a parent")
  signal(error ("Cannot use unknown \"slimhtml\" back-end as a parent"))
  error("Cannot use unknown \"%s\" back-end as a parent" slimhtml)
  org-export-register-backend(#s(org-export-backend :name custom-html-exporter :parent slimhtml :transcoders ((bold . ox-slimhtml-bold) (special-block . org-html-special-block)) :options nil :filters nil :blocks nil :menu nil))
  org-export-define-derived-backend(custom-html-exporter slimhtml :translate-alist ((bold . ox-slimhtml-bold) (special-block . org-html-special-block)))
  eval((org-export-define-derived-backend 'custom-html-exporter 'slimhtml :translate-alist '((bold . ox-slimhtml-bold) (special-block . org-html-special-block))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by freetonik** [comment]
Oh, wait, I completely messed up the order of `org-export-define-derived-backend`, my bad.
Let me try to figure this out, the problem is with my load process I think

**Comment by balddotcat** [comment]
I think the problem is a missing `autoload` declaration - hopefully this is as simple as adding one line above the org-export backend definition, but I'll have to test it.

**Comment by freetonik** [comment]
I managed to fix this by moving the loading of ox-slimhtml **after** the custom-file loading (I store it in a separate file). So, I guess, steps to reproduce this bug are potentially as follows:

1. Install `ox-slimhtml`
2. In the config, load `ox-slimhtml` first
3. Then load the custom file (`(load custom-file 'noerror)`)

**Comment by freetonik** [comment]
Geez, how dumb am I... It's totally my problem — I generate custom org backends list in my customize file. So, sorry about all this.

**Comment by balddotcat** [comment]
I usually run my publishing projects through a separate Emacs daemon, or in batch mode - with a simple `require` - so thanks for pointing out this use-case scenario!

Verified, locally, that running `(require 'ox-slimhtml)` in a fresh environment loads the `slimhtml` exporter definition; one can see the presence of the menu option in `Export Dispatcher`, as an example.

**Comment by freetonik** [comment]
Yeah, my problem was that I had re-defined the list of backends in my customize file, and that file is loaded last:

```
'(org-export-backends (quote (ascii html latex md hugo)))
```
